config/routes.rb
Rails.application.routes.draw do


  resources :posts

  devise_for :users
  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def new 
        @post = Post.new
    end

    def create
        @post = current_user.posts.new(post_params)
        # @post = Post.new(post_params.merge(user_id: current_user.id))
        # @post.user_id = current_user.id
        if @post.save
            redirect_to root_path, notice: "Post was successfully created."
        else
            render :new, status: :unprocessable_entity
        end
    end

    private 

        def post_params
            params.require(:post).permit(:body)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <header>
      <%= render 'pages/header' %>
    </header>

    <% if notice %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% elsif alert %>
      <div class="alert alert-success" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Members-only', root_path, class:"navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
        <% if !current_user %>
            <li class="nav-item">
                <%= link_to 'Sign up', new_user_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to 'Sign in', new_user_session_path, class:"nav-link" %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Sign out", destroy_user_session_path, "data-turbo-method": :delete, class:"nav-link" %>
            </li>
            <li>
                <%= link_to "Create post", new_post_path, class:"nav-link" %>
            </li>
        <% end %>
        </ul>
    </div>
</nav>

app/views/pages/home.html.erb
<h1 class="text-center">
    Members only app.
</h1>

<h3 class="text-center">All posts.</h3>

<div class="text-center">
    <% @posts.each do |post| %>
    <br>
        <div class="card mr-auto ml-auto" style="width: 50rem;">
            <div class="card-body">
                <p class="card-text">
                    <%= post.body %>
                    <br>
                    <b><%= post.user.email if current_user %></b>
            </div>
        </div>
    <% end %>

</div>

app/views/posts/_form.html.erb
<%= form_with model: @post do |form| %>
    <div>
        <%= form.label "Create post" %><br>
        <%= form.text_area :body %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/posts/new.html.erb
<h2>
    Create post.
</h2>

<%= render 'posts/form' %>